### ISSUE TITLE
Is there way to make it work with intersection?

### ISSUE THREAD

**Issue by moltar** [jgreene/io-ts-derive-class#1]
```ts
export const FooType = t.intersection([
  t.type({
    id: t.string,
  }),
  // optional
  t.partial({
    foo: t.string,
  })
])
export class Foo extends tdc.DeriveClass(FooType) { }
```

Getting:

> Property 'props' is missing in type

**Comment by jgreene** [comment]
It is probably possible but I'm not sure what the use case is here.  Intersection types between interfaces can likely be flattened to interface types instead.  Using DeriveClass will set defaults for you on instantiation of the class so the partial is probably unnecessary.  You can likely get the result you want doing the below:

```
const FooType = t.type({
    id: t.string,
    foo: t.union([t.string, t.undefined])
})

class Foo extends tdc.DeriveClass(FooType) { }

const foo1 = new Foo({ id: 'FirstFoo' })
// foo1.foo === undefined
const foo2 = new Foo({ id: 'SecondFoo', foo: 'foo' })
// foo2.foo === 'foo'
```

**Comment by moltar** [comment]
Ok, thanks for the pointer. Did not consider `t.union([t.string, t.undefined])`!
